### ISSUE TITLE
Error on join and crash when using the character inventory

### ISSUE THREAD

**Issue by reisnersteve** [G3rste/animalcages#8]
The mod causes this error when a player joins: 

`21.1.2024 22:40:03 [Server Error] Mod exception: OnPlayerJoin
21.1.2024 22:40:03 [Server Error] Exception: Type is not expected, and no contract can be inferred: Animalcages.CageConfig
   at ProtoBuf.Meta.TypeModel.ThrowUnexpectedType(Type type) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 1472
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 196
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 224
   at Vintagestory.API.Util.SerializerUtil.Serialize[T](T data) in VintagestoryApi\Util\SerializerUtil.cs:line 21
   at Vintagestory.Server.NetworkChannel.GenPacket[T](T message) in VintagestoryLib\Server\API\NetworkChannel.cs:line 89
   at Vintagestory.Server.NetworkChannel.BroadcastPacket[T](T message, IServerPlayer[] exceptPlayers) in VintagestoryLib\Server\API\NetworkChannel.cs:line 83
   at Animalcages.Animalcages.<>c__DisplayClass2_0.<StartServerSide>b__0(IServerPlayer byPlayer) in E:\Workspace\vintage_story_mods\animalcages\src\AnimalCages.cs:line 66
   at Vintagestory.Server.ServerEventManager.TriggerPlayerJoin(IServerPlayer player) in VintagestoryLib\Server\ServerEventManager.cs:line 659`

Also when pressing 'C' to access the player inventory it causes a crash with the following log: 

`Running on 64 bit Windows 10.0.22631.0 with 16191 MB RAM
Game Version: v1.19.1 (Stable)
21.01.2024 22:43:40: Critical error occurred
Loaded Mods: bettercrates@1.7.0, butchering@1.1.0, chiseltools@1.10.1, dirtyoldsack@1.0.1, millwright@1.1.3, primitivesurvival@3.4.5, qptech@1.14.2, game@1.19.1, animalcages@3.0.1, commonlib@2.3.2, medievalexpansion@3.13.1, outlawmod@1.2.0, paxel@1.4.3, petai@2.2.1, scarecrow@1.4.1, storagecontroller@1.0.4, vanvar@3.3.0, vinconomy@0.2.0, creative@1.19.1, survival@1.19.1, cats@2.0.1, feverstonehorses@1.6.0, playercorpse@1.9.0, wolftaming@2.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ModSystemRiftWeather.ModSystemDrifterWeather_OnEnvText(StringBuilder sb) in VSSurvivalMod\Systems\Rifts\RiftWeather.cs:line 85
   at Vintagestory.GameContent.CharacterExtraDialogs.getEnvText() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 161
   at Vintagestory.GameContent.CharacterExtraDialogs.ComposeEnvGui() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 86
   at Vintagestory.GameContent.CharacterExtraDialogs.Dlg_ComposeExtraGuis() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 56
   at Vintagestory.Client.NoObf.GuiDialogCharacter.ComposeGuis() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogCharacter.cs:line 137
   at Vintagestory.Client.NoObf.GuiDialogCharacter.OnGuiOpened() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogCharacter.cs:line 226
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 288
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 268
   at Vintagestory.API.Client.GuiDialog.Toggle() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 338
   at Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 405
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 365
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls) in VintagestoryLib\Client\HotkeyManager.cs:line 338
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1747
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 310
   at Vintagestory.Client.ScreenManager.OnKeyDown(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 848
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 247
   at OpenTK.Windowing.Desktop.NativeWindow.OnKeyDown(KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
`

When removing animalcages none of the above issues occur.

**Comment by G3rste** [comment]
What version of Vintage Story and Animalcages are you using?
Are you playing locally or on a server?
Does it happen if you disable all other mods?

**Comment by zell97** [comment]
I am experiencing the exact same issue.

   23.1.2024 00:36:03 [Error] Exception: Type is not expected, and no contract can be inferred: Animalcages.CageConfig
   at ProtoBuf.Meta.TypeModel.ThrowUnexpectedType(Type type) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 1472
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 196
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context) in C:\Code\pb-net_24\src\protobuf-net\Meta\TypeModel.cs:line 224
   at Vintagestory.API.Util.SerializerUtil.Serialize[T](T data) in VintagestoryApi\Util\SerializerUtil.cs:line 21
   at Vintagestory.Server.NetworkChannel.GenPacket[T](T message) in VintagestoryLib\Server\API\NetworkChannel.cs:line 89
   at Vintagestory.Server.NetworkChannel.BroadcastPacket[T](T message, IServerPlayer[] exceptPlayers) in VintagestoryLib\Server\API\NetworkChannel.cs:line 83
   at Animalcages.Animalcages.<>c__DisplayClass2_0.<StartServerSide>b__0(IServerPlayer byPlayer) in E:\Workspace\vintage_story_mods\animalcages\src\AnimalCages.cs:line 66
   at Vintagestory.Server.ServerEventManager.TriggerPlayerJoin(IServerPlayer player) in VintagestoryLib\Server\ServerEventManager.cs:line 659
   
   **Vintage Story Ver. 1.19.1
Only appears to happen in a multiplayer setting, in single player everything works fine.
In multiplayer, when a player joins, they are greeted with the character customization screen even though they are existing players.
Upon hitting the "C" key to open player menu, the client will crash and throw the above error.
Have not run this as just the only mod running.

Server is being hosted through the dedicated server console on my own pc.

I have deleted both the mod and modconfig twice trying to see if maybe a bad download or a bad config, still happens every time. **

Client Crash Log:

Game Version: v1.19.1 (Stable)
1/23/2024 12:36:25 AM: Critical error occurred
Loaded Mods: hqzlights@1.1.1, millwright@1.1.3, orepulverizer@1.1.1, primitivesurvival@3.4.5, sortablestorage@2.2.1, specializedbags-18Slot@0.4.2, sticksfromfirewood@1.0.0, translocatorengineeringredux@1.4.9, game@1.19.1, alchemy@1.6.23, animalcages@3.0.1, fromgoldencombs@1.4.25, herbarium@1.0.4, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, petai@2.2.2, stillnecessaries@1.1.0, stonebakeoven@1.1.3, usefulstuff17@1.3.0, creative@1.19.1, survival@1.19.1, cats@2.0.1, foxtaming@1.4.0, wildcraftfruit@1.1.0, wildcrafttree@1.0.0, wolftaming@2.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ModSystemRiftWeather.ModSystemDrifterWeather_OnEnvText(StringBuilder sb) in VSSurvivalMod\Systems\Rifts\RiftWeather.cs:line 85
   at Vintagestory.GameContent.CharacterExtraDialogs.getEnvText() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 161
   at Vintagestory.GameContent.CharacterExtraDialogs.ComposeEnvGui() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 86
   at Vintagestory.GameContent.CharacterExtraDialogs.Dlg_ComposeExtraGuis() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 56
   at Vintagestory.Client.NoObf.GuiDialogCharacter.ComposeGuis() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogCharacter.cs:line 137
   at Vintagestory.Client.NoObf.GuiDialogCharacter.OnGuiOpened() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogCharacter.cs:line 226
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 293
   at Vintagestory.API.Client.GuiDialog.Toggle() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 338
   at Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 405
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 375
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls) in VintagestoryLib\Client\HotkeyManager.cs:line 338
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1747
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 310
   at Vintagestory.Client.ScreenManager.OnKeyDown(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 848
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 247
   at OpenTK.Windowing.Desktop.NativeWindow.OnKeyDown(KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by G3rste** [comment]
Does [this](https://github.com/G3rste/animalcages/files/14028885/animalcages.zip) solve the issues?

**Comment by zell97** [comment]
No, still having the same issue. Below is the crash log from the crash reporter.

Running on 64 bit Windows 10.0.19045.0 with 32711 MB RAM
Game Version: v1.19.1 (Stable)
1/23/2024 5:31:57 PM: Critical error occurred
Loaded Mods: hqzlights@1.1.1, millwright@1.1.3, orepulverizer@1.1.1, primitivesurvival@3.4.5, sortablestorage@2.2.1, specializedbags-18Slot@0.4.2, sticksfromfirewood@1.0.0, translocatorengineeringredux@1.4.9, game@1.19.1, alchemy@1.6.23, animalcages@3.0.1, fromgoldencombs@1.4.25, herbarium@1.0.4, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, petai@2.2.2, stillnecessaries@1.1.0, stonebakeoven@1.1.3, usefulstuff17@1.3.0, creative@1.19.1, survival@1.19.1, cats@2.0.1, foxtaming@1.4.0, wildcraftfruit@1.1.0, wildcrafttree@1.0.0, wolftaming@2.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ModSystemRiftWeather.ModSystemDrifterWeather_OnEnvText(StringBuilder sb) in VSSurvivalMod\Systems\Rifts\RiftWeather.cs:line 85
   at Vintagestory.GameContent.CharacterExtraDialogs.getEnvText() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 161
   at Vintagestory.GameContent.CharacterExtraDialogs.ComposeEnvGui() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 86
   at Vintagestory.GameContent.CharacterExtraDialogs.Dlg_ComposeExtraGuis() in VSEssentials\Systems\CharacterExtraDialogs.cs:line 56
   at Vintagestory.Client.NoObf.GuiDialogCharacter.ComposeGuis() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogCharacter.cs:line 137
   at Vintagestory.Client.NoObf.GuiDialogCharacter.OnGuiOpened() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogCharacter.cs:line 226
   at Vintagestory.API.Client.GuiDialog.TryOpen(Boolean withFocus) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 288
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 268
   at Vintagestory.API.Client.GuiDialog.Toggle() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 338
   at Vintagestory.API.Client.GuiDialog.OnKeyCombinationToggle(KeyCombination viaKeyComb) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 405
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack) in VintagestoryLib\Client\HotkeyManager.cs:line 365
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls) in VintagestoryLib\Client\HotkeyManager.cs:line 338
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1747
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 310
   at Vintagestory.Client.ScreenManager.OnKeyDown(KeyEvent e) in VintagestoryLib\Client\ScreenManager.cs:line 848
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 247
   at OpenTK.Windowing.Desktop.NativeWindow.OnKeyDown(KeyboardKeyEventArgs e)
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 1
==================================
{ TimeGenerated = 1/23/2024 12:36:29 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.1.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x48c0
Faulting application start time: 0x01da4dc613079a66
Faulting application path: C:\Users\Bradley\AppData\Roaming\Vintagestory_New\Vintagestory.exe
Faulting module path: C:\Users\Bradley\AppData\Roaming\Vintagestory_New\Lib\openal32.dll
Report Id: 9e3f4b95-96d5-4c51-aafa-7a28369067cf
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by G3rste** [comment]
How about this one?
[animalcages.zip](https://github.com/G3rste/animalcages/files/14043073/animalcages.zip)

**Comment by zell97** [comment]
It appears to have been fixed! If anything else weird happens, I'll post an issue.

Thanks!

**Comment by G3rste** [comment]
Wuhuuu thanks for testing
